#!/usr/bin/env bash
# Install the load balancer


sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get -y install haproxy
sudo sed -i 's/ENABLED=0/ENABLED=1/' /etc/default/haproxy
sudo cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.original
sudo sed -i "$ a\listen 364-lb-01\n\tbind *:80\n\tmode http\n\tbalance roundrobin\n\toption httpclose\n\toption forwardfor\n\tserver 364-web-02 34.239.160.58:80 check\n\tserver 364-web-01 34.73.142.150:80 check" /etc/haproxy/haproxy.cfg
sudo service haproxy start
